팀J 프로젝트 제출
DVL-Sejong/openlab pull request #4
Opened 2024-12-18 09:43 UTC by HOIVVVV

[팀J 프로젝트 제출](https://github.com/DVL-Sejong/openlab/commit/2cd9e670056c362fd90d19f68d51feb7f5876889)

2024-12-20 00:29 UTC, Seongbuming requested changes

2024-12-20 00:29 UTC, Seongbuming commented on lectures/Web-based System (2024-2)/team-J/ShipClassifier/webHW5_TeamJ/shipver4/ReadMe.txt
이 내용을 `../team-J/readme.md`로 옮겨주세요.

2024-12-20 13:43 UTC, HOIVVVV commented on lectures/Web-based System (2024-2)/team-J/ShipClassifier/webHW5_TeamJ/shipver4/ReadMe.txt
넵 수정했습니다.

2024-12-21 19:45 UTC, Seongbuming approved these changes

2024-12-21 19:45 UTC, merged